jdncDeveloper/JDNC_Library_BE

.gitignore
src/main/java/com/example/jdnc_library/config/SecurityConfig.java

[feature/#5] securityConfig 수정

---

src/main/java/com/example/jdnc_library/config/JpaConfig.java
src/main/java/com/example/jdnc_library/domain/WriterEntity.java

[feature/#8] entity 추적

---

.gitignore

[feature/#8] git ignore 추가

---

src/main/java/com/example/jdnc_library/domain/book/model/Book.java
src/main/java/com/example/jdnc_library/domain/book/model/BookInfo.java
src/main/java/com/example/jdnc_library/domain/book/model/BorrowInfo.java
src/main/java/com/example/jdnc_library/domain/book/model/CollectionInfo.java
src/main/java/com/example/jdnc_library/domain/book/repository/BookRepository.java
src/main/java/com/example/jdnc_library/domain/book/repository/BorrowRepository.java
src/main/java/com/example/jdnc_library/domain/book/repository/CollectionRepository.java
src/main/java/com/example/jdnc_library/feature/book/controller/BookController.java
src/main/java/com/example/jdnc_library/feature/book/controller/BorrowController.java
src/main/java/com/example/jdnc_library/feature/book/controller/SearchController.java
src/main/java/com/example/jdnc_library/feature/book/model/BookDTO.java
src/main/java/com/example/jdnc_library/feature/book/model/BookRequest.java
src/main/java/com/example/jdnc_library/feature/book/model/BorrowDTO.java
src/main/java/com/example/jdnc_library/feature/book/model/BorrowRequest.java
src/main/java/com/example/jdnc_library/feature/book/model/SearchRequest.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java
src/main/java/com/example/jdnc_library/feature/tutorial/controller/TutorialController.java
src/main/resources/application.yml

[feature/#4] 도서 대출 반납 일부

---

src/main/java/com/example/jdnc_library/config/SecurityConfig.java

[feature/#18] cors disable 설정

---

src/main/java/com/example/jdnc_library/config/CorsConfig.java
src/main/java/com/example/jdnc_library/config/SecurityConfig.java

[feature/#18] cors Filter 추가 및 기존 충돌나던 코드 수정

---

src/main/java/com/example/jdnc_library/config/CorsConfig.java

[feature/#18] corsFilter 전체 헤더 허용에서 사용하는 일부만 허용

---

.gitignore
build.gradle
src/main/java/com/example/jdnc_library/feature/mail/contorller/SendMailTestController.java
src/main/java/com/example/jdnc_library/feature/mail/service/EmailService.java
src/main/java/com/example/jdnc_library/feature/manager/controller/ManagerController.java
src/main/java/com/example/jdnc_library/feature/manager/service/ManagerService.java
src/main/java/com/example/jdnc_library/feature/member/controller/MemberController.java
src/main/java/com/example/jdnc_library/feature/member/model/MemberDTO.java
src/main/java/com/example/jdnc_library/feature/member/service/MemberService.java
src/main/resources/application.yml

1. smtp 기본 기능 구현
2. 유저 Role, 정보 요청 api구현
1. smtp를 위한 gradle추가, yml 추가되었음
2. smtp는 추가 회의를 통해 보완 필요
3. 일부 기능(유저 리스트 요청)을 manager -> member로 위치 수정

smtp, 유저정보 및 role리턴,

---

src/main/java/com/example/jdnc_library/config/CorsConfig.java
src/main/resources/application.yml

[feature/#30] 헤더 추출 가능 헤더 추가

---

src/main/java/com/example/jdnc_library/feature/book/controller/BookController.java
src/main/java/com/example/jdnc_library/feature/book/controller/BorrowController.java
src/main/java/com/example/jdnc_library/feature/book/controller/SearchController.java

[feature/#35]controller 메서드 public 변경

---

src/main/java/com/example/jdnc_library/domain/WriterEntity.java

[feature/#37] Unique 키값 문제 해결

---

src/main/java/com/example/jdnc_library/domain/book/repository/BookRepository.java
src/main/java/com/example/jdnc_library/feature/book/controller/BorrowController.java
src/main/java/com/example/jdnc_library/feature/book/controller/SearchController.java
src/main/java/com/example/jdnc_library/feature/book/model/BorrowListDTO.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java

도서 검색 기능/ 대출 검색 메서드/ LocalDate JSON Parse

[feature/#21]도서 검색 기능/ 대출 검색 메서드/ LocalDate JSON Parse

---

src/main/java/com/example/jdnc_library/config/CorsConfig.java
src/main/java/com/example/jdnc_library/config/SecurityConfig.java
src/main/java/com/example/jdnc_library/domain/member/model/Member.java
src/main/java/com/example/jdnc_library/exception/clienterror/_400/TokenNotExpiredException.java
src/main/java/com/example/jdnc_library/security/controller/RefreshController.java
src/main/java/com/example/jdnc_library/security/filter/JwtAuthenticationFilter.java
src/main/java/com/example/jdnc_library/security/filter/JwtAuthorizationFilter.java
src/main/java/com/example/jdnc_library/security/jwt/TokenProvider.java
src/main/java/com/example/jdnc_library/security/service/LmsCrawlerService.java
src/main/java/com/example/jdnc_library/security/service/RefreshService.java
src/main/resources/application.yml

[feature/#34] 리프레시 토큰 갱신 기능 추가

---

src/main/java/com/example/jdnc_library/config/CorsConfig.java
src/main/java/com/example/jdnc_library/security/jwt/TokenProvider.java
src/main/resources/application.yml

[feature/#34] 토큰 갱신 시간 조정

---

src/main/java/com/example/jdnc_library/security/jwt/TokenProvider.java

[feature/#34] 프론트엔드 요청으로 토큰 갱신 시간 재조정

---

src/main/java/com/example/jdnc_library/security/jwt/TokenProvider.java

[feature/#34] 프론트엔드 요청으로 토큰 갱신 시간 재조정2

---

src/main/java/com/example/jdnc_library/domain/book/repository/BookRepository.java
src/main/java/com/example/jdnc_library/domain/book/repository/BorrowRepository.java
src/main/java/com/example/jdnc_library/feature/book/controller/BookController.java
src/main/java/com/example/jdnc_library/feature/book/controller/BorrowController.java
src/main/java/com/example/jdnc_library/feature/book/controller/SearchController.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java

[feature/#46]BookGroup 검색기능/ adminCheck test 기능

---

src/main/java/com/example/jdnc_library/converter/BookGroupConverter.java
src/main/java/com/example/jdnc_library/domain/book/model/BookGroup.java
src/main/java/com/example/jdnc_library/domain/book/model/BookInfo.java
src/main/java/com/example/jdnc_library/feature/book/DTO/BookRequest.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java

[feature/#48] BookGroup Enum 컨버터 제어

---

build.gradle
src/main/java/com/example/jdnc_library/config/SecurityConfig.java
src/main/resources/application.yml

[feature/#50] health check 기능 추가

---

src/main/java/com/example/jdnc_library/domain/book/repository/BorrowRepository.java
src/main/java/com/example/jdnc_library/domain/mail/model/MailTemplate.java
src/main/java/com/example/jdnc_library/domain/mail/repository/MailTemplateRepository.java
src/main/java/com/example/jdnc_library/feature/convert/DTO/ConvertRangeDTO.java
src/main/java/com/example/jdnc_library/feature/mail/DTO/MailTemplateDTO.java
src/main/java/com/example/jdnc_library/feature/mail/contorller/SendMailTestController.java
src/main/java/com/example/jdnc_library/feature/mail/service/EmailService.java

메일 서비스 기본 틀 구축
- (사용자의 입장에서) 이전에 작성한 글(템플릿) 불러오기
- 수정한 글(혹은 수정하지 않은)을 책을 대여중인 인원들에게 메일 전송
- 수정한글을 저장

메일 서비스 기본 틀 구축

---

build.gradle
src/main/java/com/example/jdnc_library/domain/book/model/BookInfo.java
src/main/java/com/example/jdnc_library/feature/book/DTO/BookRequest.java
src/main/java/com/example/jdnc_library/feature/book/controller/SearchController.java
src/main/java/com/example/jdnc_library/feature/book/repository/BookInfoQueryRepository.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java
src/main/java/com/example/jdnc_library/util/Querydsl4ExpressionUtil.java
src/main/java/com/example/jdnc_library/util/Querydsl4RepositorySupport.java

[feature/#55] QueryDSL 도입

---

src/main/java/com/example/jdnc_library/feature/book/repository/BookInfoQueryRepository.java
src/main/java/com/example/jdnc_library/util/Querydsl4ExpressionUtil.java
src/main/resources/application.yml

[feature/#55] query문 개선

---

src/main/java/com/example/jdnc_library/domain/member/model/Member.java
src/main/java/com/example/jdnc_library/domain/member/repository/MemberRepository.java
src/main/java/com/example/jdnc_library/feature/convert/service/ConvertToExelFileService.java
src/main/java/com/example/jdnc_library/feature/manager/service/ManagerService.java
src/main/java/com/example/jdnc_library/feature/member/service/MemberService.java
src/main/java/com/example/jdnc_library/init/AdminInitializer.java
src/main/java/com/example/jdnc_library/security/controller/LoginTestController.java
src/main/java/com/example/jdnc_library/security/filter/JwtAuthenticationFilter.java
src/main/java/com/example/jdnc_library/security/model/LmsTotalInfo.java
src/main/java/com/example/jdnc_library/security/model/LoginInfo.java
src/main/java/com/example/jdnc_library/security/model/PrincipalDetails.java
src/main/java/com/example/jdnc_library/security/service/LmsCrawlerService.java
src/main/java/com/example/jdnc_library/security/service/LmsService.java
src/main/java/com/example/jdnc_library/security/service/PrincipalDetailsService.java
src/main/java/com/example/jdnc_library/util/RegexUtil.java
src/main/resources/application.yml

[feature/#53] 관리자 로그인 및 최초 관리자 자동 등록

---

src/main/java/com/example/jdnc_library/domain/member/model/Member.java

[feature/#64] 변화된 컬럼에 맞는 index 처리

---

src/main/java/com/example/jdnc_library/feature/book/controller/BookController.java
src/main/java/com/example/jdnc_library/feature/book/controller/BorrowController.java
src/main/java/com/example/jdnc_library/feature/book/controller/SearchController.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java
src/main/java/com/example/jdnc_library/feature/book/service/BorrowService.java
src/main/java/com/example/jdnc_library/feature/book/service/SearchService.java

[feature/#62]Exception 처리 및 파라미터 Positive처리

---

src/main/java/com/example/jdnc_library/feature/naverAPI/DTO/ExtractionBookInfoDTO.java
src/main/java/com/example/jdnc_library/feature/naverAPI/DTO/NaverAPIDTO.java
src/main/java/com/example/jdnc_library/feature/naverAPI/controller/NaverAPIController.java
src/main/java/com/example/jdnc_library/feature/naverAPI/service/NaverAPIService.java

네이버 API를 사용해서 검색한 책의 정보를 가져와 리턴해주는 기능 구현
title, page 파라미터를 받아서 네이버 api가 지원하는 페이징도 사용.

네이버API를 통한 도서정보 수집

---

.gitignore
src/main/java/com/example/jdnc_library/feature/naverAPI/service/NaverAPIService.java
src/main/resources/application.yml

하드코딩 되어있던 naver api의 id값과 secret 변수처리
상동

시크릿키 및 id 변수처리

---

src/main/java/com/example/jdnc_library/domain/member/repository/MemberRepository.java
src/main/java/com/example/jdnc_library/feature/manager/service/ManagerService.java
src/main/java/com/example/jdnc_library/feature/member/controller/MemberController.java
src/main/java/com/example/jdnc_library/feature/member/service/MemberService.java
src/main/resources/application-naverapi.yml

도서지기 기능 수정
도서지기 임명 / 해제 / 정보획득 기능의 오류 수정
도서지기 임명을 위한 유저 검색 기능 추가

도서지기 기능 수정

---

src/main/java/com/example/jdnc_library/config/WebConfig.java
src/main/java/com/example/jdnc_library/feature/book/controller/AdminBookCollectionController.java
src/main/java/com/example/jdnc_library/feature/book/controller/BookController.java
src/main/java/com/example/jdnc_library/feature/book/controller/BorrowController.java
src/main/java/com/example/jdnc_library/feature/book/service/BorrowService.java

[feature/#68] 남은 컨트롤러 path 정리

---

src/main/java/com/example/jdnc_library/feature/member/controller/MemberController.java
src/main/java/com/example/jdnc_library/feature/member/service/MemberService.java

MemberList 페이지네이션 구현
페이지는 쿼리 파라미터로 받음
15개씩 리턴

memberList pagenation

---

src/main/java/com/example/jdnc_library/feature/member/DTO/MemberDTO.java
src/main/java/com/example/jdnc_library/feature/member/DTO/PagedMemberDTO.java
src/main/java/com/example/jdnc_library/feature/member/controller/MemberController.java
src/main/java/com/example/jdnc_library/feature/member/service/MemberService.java

페이지네이션 total page number 얻을 수 있도록 수정

페이지네이션 오류 수정 및 기능추가

---

.gitignore
src/main/java/com/example/jdnc_library/feature/book/repository/BookInfoQueryRepository.java
src/main/resources/application-production.yml
src/main/resources/application.yml

[feature/#74] production yml secret env 처리

---

src/main/java/com/example/jdnc_library/feature/book/controller/BorrowController.java

[feature/#81] 코드 오류 수정

---

src/main/java/com/example/jdnc_library/domain/book/repository/BorrowRepository.java
src/main/java/com/example/jdnc_library/feature/book/controller/AdminBookController.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java

[feature/#84] 월별 관리목록 및 관리자 확인이 필요한 책 목록 메서드 수정

---

src/main/java/com/example/jdnc_library/domain/book/model/BorrowInfo.java
src/main/java/com/example/jdnc_library/feature/book/DTO/BorrowListDTO.java
src/main/java/com/example/jdnc_library/feature/book/repository/BorrowInfoQueryRepository.java

[feature/#81] query join 구문 수정

---

src/main/java/com/example/jdnc_library/domain/book/repository/BorrowRepository.java
src/main/java/com/example/jdnc_library/feature/book/DTO/BorrowListDTO.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java

[feature/#87] LocalDateTime 타입 수정

---

src/main/java/com/example/jdnc_library/exception/GlobalRestExceptionHandler.java
src/main/java/com/example/jdnc_library/security/filter/JwtAuthorizationFilter.java
src/main/java/com/example/jdnc_library/security/jwt/TokenProvider.java

[feature/#89] 에러 핸들링 및 토큰 없을시 에러 처리 해제

---

src/main/java/com/example/jdnc_library/feature/book/controller/AdminBookCollectionController.java
src/main/java/com/example/jdnc_library/feature/book/controller/AdminBookController.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java

[feature/#93] 책정보 & 소장정보 삭제 기능

---

src/main/java/com/example/jdnc_library/feature/book/controller/AdminBookCollectionController.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java

[feature/#96] 월간 대출 현황 수정 및 소실 개별 처리

---

src/main/java/com/example/jdnc_library/domain/book/repository/BorrowRepository.java
src/main/java/com/example/jdnc_library/feature/convert/controller/ConvertController.java
src/main/java/com/example/jdnc_library/feature/convert/service/ConvertToExelFileService.java
src/main/java/com/example/jdnc_library/feature/mail/DTO/MailServiceDTO.java
src/main/java/com/example/jdnc_library/feature/mail/contorller/SendMailController.java
src/main/java/com/example/jdnc_library/feature/mail/service/EmailService.java

메일 서비스 async추가 및 기능 변경
기존의 메일 전송 방식을 취소하고 미반납 항목 개별 메일 전송으로 수정
비동기 처리

메일 서비스 async추가 및 기능 변경

---

src/main/java/com/example/jdnc_library/feature/mail/contorller/SendMailController.java
src/main/java/com/example/jdnc_library/feature/mail/service/EmailService.java
src/main/java/com/example/jdnc_library/feature/mail/service/MakeMailTemplate.java

[feature/#100] 메일 서비스 리팩토링

---

src/main/java/com/example/jdnc_library/feature/book/DTO/BookListDTO.java
src/main/java/com/example/jdnc_library/feature/book/DTO/BorrowListDTO.java
src/main/java/com/example/jdnc_library/feature/book/repository/BookInfoQueryRepository.java
src/main/java/com/example/jdnc_library/feature/book/repository/BorrowInfoQueryRepository.java

[feature/#101] DTO 오류 수정

---

src/main/java/com/example/jdnc_library/converter/jpa/BookGroupJpaConverter.java
src/main/java/com/example/jdnc_library/domain/book/model/BookGroup.java

[hotfix/BookGroupEnumConvertFix] Enum 조회 불가 처리 수정

---

src/main/java/com/example/jdnc_library/domain/book/model/BorrowInfo.java
src/main/java/com/example/jdnc_library/domain/book/model/CollectionInfo.java
src/main/java/com/example/jdnc_library/feature/book/DTO/BookNumberRequest.java
src/main/java/com/example/jdnc_library/feature/book/DTO/BorrowListDTO.java
src/main/java/com/example/jdnc_library/feature/book/DTO/CreateCollectionDTO.java
src/main/java/com/example/jdnc_library/feature/book/DTO/ReturnRequest.java
src/main/java/com/example/jdnc_library/feature/book/controller/AdminBookCollectionController.java
src/main/java/com/example/jdnc_library/feature/book/controller/BorrowController.java
src/main/java/com/example/jdnc_library/feature/book/service/BorrowService.java

[feature/#107] GET을 제외한 메서드 파라미터를 RequestBody로 변경

---

src/main/java/com/example/jdnc_library/feature/book/repository/BorrowInfoQueryRepository.java

[feature/#109] state -> floor 쿼리DSL수정

---

src/main/java/com/example/jdnc_library/feature/book/repository/BorrowInfoQueryRepository.java

[feature/#111] 관리자 미확인 목록 문제 해결

---

src/main/java/com/example/jdnc_library/exception/clienterror/_400/EntityExistsException.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java
src/main/java/com/example/jdnc_library/feature/book/service/BorrowService.java

[feature/#113] detached entity passed to persist 오류 fix

---

src/main/java/com/example/jdnc_library/feature/convert/controller/ConvertController.java
src/main/java/com/example/jdnc_library/feature/convert/service/ConvertToExelFileService.java

엑셀 기능 수정 및 리팩토링 진행
1~5로 선언했던 cell변수를 배열로 통합
반납함 위치 반영

엑셀 기능 수정 및 리팩토링

---

src/main/java/com/example/jdnc_library/domain/book/repository/CollectionRepository.java
src/main/java/com/example/jdnc_library/feature/book/DTO/CountDTO.java
src/main/java/com/example/jdnc_library/feature/book/controller/BookController.java
src/main/java/com/example/jdnc_library/feature/book/service/SearchService.java

[feature/#117] 대출가능 책 및 소장 책 count

---

build.gradle
src/main/java/com/example/jdnc_library/config/AwsConfig.java
src/main/java/com/example/jdnc_library/config/SecurityConfig.java
src/main/java/com/example/jdnc_library/exception/GlobalRestExceptionHandler.java
src/main/java/com/example/jdnc_library/feature/aws/controller/ImageSaveController.java
src/main/java/com/example/jdnc_library/feature/aws/dto/FileRequest.java
src/main/java/com/example/jdnc_library/feature/aws/service/S3Service.java
src/main/java/com/example/jdnc_library/security/jwt/JwtAccessDeniedHandler.java
src/main/java/com/example/jdnc_library/security/jwt/JwtAuthenticationEntryPoint.java
src/main/resources/application-production.yml
src/main/resources/application.yml

[feature/#116] aws 이미지 저장 및 에러처리 헨들링

---

src/main/java/com/example/jdnc_library/feature/book/DTO/BookAvailableDTO.java
src/main/java/com/example/jdnc_library/feature/book/DTO/BookDetailDTO.java
src/main/resources/application.yml

[feature/#120] book Available 개별 표기

---

src/main/java/com/example/jdnc_library/domain/book/repository/BorrowRepository.java
src/main/java/com/example/jdnc_library/feature/book/controller/AdminBookCollectionController.java
src/main/java/com/example/jdnc_library/feature/book/controller/AdminBookController.java
src/main/java/com/example/jdnc_library/feature/book/service/BorrowService.java

[feature/#123] 현재 대출 중인 책 및 반납한 책 count

---

src/main/java/com/example/jdnc_library/feature/book/DTO/BorrowListDTO.java
src/main/java/com/example/jdnc_library/feature/book/repository/BorrowInfoQueryRepository.java

[feature/#123] BorrowListDTO adminCheck 추가

---

src/main/java/com/example/jdnc_library/domain/TimeEntity.java
src/main/java/com/example/jdnc_library/domain/book/model/BookInfo.java
src/main/java/com/example/jdnc_library/domain/book/model/BorrowInfo.java
src/main/java/com/example/jdnc_library/domain/book/model/CollectionInfo.java
src/main/java/com/example/jdnc_library/feature/book/repository/BorrowInfoQueryRepository.java
src/main/java/com/example/jdnc_library/feature/book/service/BookService.java

[feature/#126] soft delete 적용

---

src/main/java/com/example/jdnc_library/feature/book/repository/BookInfoQueryRepository.java
src/main/java/com/example/jdnc_library/feature/book/repository/CollectionInfoQueryRepository.java

[feature/#126] 나머지 query dsl soft delete 적용

---

README.md

[feature/#130] README 작성

---

src/main/java/com/example/jdnc_library/feature/convert/controller/ConvertController.java
src/main/java/com/example/jdnc_library/feature/convert/service/ConvertToExelFileService.java
src/main/java/com/example/jdnc_library/feature/convert/service/ExcelBookListWriter.java
src/main/java/com/example/jdnc_library/feature/convert/service/ExcelBorrowListWriter.java
src/main/resources/application.yml

ConvertToExcelFileService 리팩토링
내부 메소드를 소분화

excelService 리팩토링

---

src/main/java/com/example/jdnc_library/security/filter/JwtAuthenticationFilter.java
src/main/java/com/example/jdnc_library/security/model/PrincipalDetails.java

[hotfix/로그인 오류시 에러 핸들링] PrincipalDetails null 처리 변경 및 로그인 실패로직 작성

---

src/main/java/com/example/jdnc_library/feature/convert/controller/ConvertController.java
src/main/java/com/example/jdnc_library/feature/convert/service/ConvertToExelFileService.java
src/main/java/com/example/jdnc_library/init/BookInfoInitializer.java

[Hotfix/excel] error fix
